services:
    web:
        container_name: web
        build: ./web
        restart: always
        volumes:
            - ./web/conf.d/:/etc/nginx/conf.d
        ports:
            - 80:80
    app:
        container_name: app
        build: ./app
        restart: always
        volumes:
            - ./app:/app
        expose:
            - 8000
        depends_on:
            - web
            - db
    db:
        container_name: db
        restart: always
        build: ./db
        expose:
            - 3306
        volumes:
            - ./db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=1234
            - MYSQL_DATABASE=laravel
    phpmyadmin:
        container_name: phpmyadmin
        restart: always
        build: ./phpmyadmin
        ports:
            - 81:80
        environment:
            - PMA_ARBITRARY =1
            - PMA_HOST=db
            - PMA_PORT=3306
        depends_on:
            - db
